apt-get install busybox curl rsync build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler wget tar file lvm
git clone https://github.com/Ysurac/openmptcprouter.git
cd openmptcprouter
git checkout master
OMR_TARGET="myplatform" OMR_FEED_SRC="master" OMR_KERNEL="6.1" ./build.sh
